### ISSUE TITLE
No Archlinux AUR package available

### ISSUE THREAD

**Issue by nomeata** [nomeata/arbtt#114]
**[Original report](https://bitbucket.org/nomeata/arbtt/issue/59) by Philipp Uhl (Bitbucket: [ph_uhl](https://bitbucket.org/ph_uhl), ).**

----------------------------------------

I just wanted to install arbtt on my arch setup and noticed, there is no package you could install.

If you don't mind, I would be willing to create and maintain the package. I did this with my own software once (https://github.com/phuhl/linux_notification_center, btw. written in haskell as well, </plug>).

Would that be ok for you and would you feature the package in the documentation?

**Comment by Konzertheld** [comment]
Package exists https://aur.archlinux.org/packages/arbtt/
