### ISSUE TITLE
X11 capture: non-exhaustive patterns in function dropTailNull

### ISSUE THREAD

**Issue by krav** [nomeata/arbtt#138]
Hi! 

I was giving this a spin and arbtt-capture appears to be broken on X11 in the latest 0.11.1 tag. 

```
# /nix/store/qrhn77c4v7d5p49zypwkin8m77ppf1pr-arbtt-0.11.1/bin/arbtt-capture ; echo $?
arbtt-capture: src/Capture/X11.hs:(127,5)-(128,45): Non-exhaustive patterns in function dropTailNull
1
```

Everything appears to work correctly after adding `dropTailNull [] = []` to `getDesktops` in X11.hs.

**Comment by nomeata** [comment]
Yuck, my bad coding practices from back then catch me. 

Although I am surprised nobody else has complained about this. I wonder if “usually” this case isn't needed. But I don't remember the details.

**Comment by nomeata** [comment]
Ah, there is a comment about that. Maybe `wcTextPropertyToTextList` got fixed? In that case, this function definitely ought to be more defensive, and handle both cases.
