### ISSUE TITLE
Receiving input from gamepad while no button is being pressed

### ISSUE THREAD

**Issue by isqnwtn** [nomeata/arbtt#140]
While the Bluetooth gamepad is connected, keeps receiving input from it while the gamepad in fact is actually turned off.
This is happening in WSL1, and the gamepad I'm using is RedGear.
even if the gamepad is turned off if the Bluetooth adapter is connected it seems to be registering some sort of input which in turn results in high activity over any app that is presently active

**Comment by nomeata** [comment]
Thanks for the report. `arbtt` gets the “last activity” information from the X server using the [`XScreenSaverQueryInfo`](https://linux.die.net/man/3/xscreensaverqueryinfo) function call.

I would assume that a screensaver would also not get activated while your gamepad is plugged in?

**Comment by isqnwtn** [comment]
Yes, I think it's something that has to be fixed with the drivers.
