### ISSUE TITLE
Dependency problems: attoparsec 0.13 requested but newer version is already installed for aeson

### ISSUE THREAD

**Issue by Konzertheld** [nomeata/arbtt#141]
The AUR (Arch User Repository) package for arbtt has been orphaned and I wanted to adopt it, but when I tried to build the current arbtt version, I ran into some dependency problems. First of all there are several upper bounds defined in the dependencies, which in general tends to break packages (and has already broken the package in the past). There is one I currently cannot resolve without a lot of effort - attoparsec exactly 0.13 is requested, but attoparsec 0.14.x is available and automatically installed when aeson is installed. What is the reason that attoparsec == 0.13.* is requested?

(This is also the reason why I did not follow up with #129)

**Comment by Konzertheld** [comment]
When I change the dependency to >= 0.13, `runhaskell Setup build` succeeds.

**Comment by nomeata** [comment]
Yes, likely most upper bounds can be bumped. I'll see if I can make a release soonish.

**Comment by Konzertheld** [comment]
Great, thanks. I made a patch and put in in the AUR so people can use the package anyway.
