### ISSUE TITLE
Issue with libffi - missing dependency or outdated

### ISSUE THREAD

**Issue by Konzertheld** [nomeata/arbtt#143]
More dependency issues, probably...

`arbtt-stats: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory`

libffi's ABI version is now 8, so version 7 was uninstalled from Arch-based systems. Version 7 is still available so I could add that as a dependency to the package. Previously, it was not necessary to list it as an explicit dependency because the Haskell compiler needs libffi anyway - but it uses the most recent version, 8.

Alternatively, if possible, the issue could be resolved if arbtt could use ABI version 8, too.

**Comment by nomeata** [comment]
That's odd, and smells more like a problem with the Arch package than the actual source. Maybe the package you tried to install was built against older libffi?

**Comment by Konzertheld** [comment]
The package pulls the source from Hackage and then uses `runhaskell Setup configure` and `build`, apart from that it does little more than making sure dependencies are installed (not taking care of libffi because that is not mentioned as a dependency on Hackage). As libffi ABI 7 was not installed at the time of building, I do not see how haskell could have built against it.

**Comment by nomeata** [comment]
Me neither :-)

**Comment by Konzertheld** [comment]
damn I know what happened. I had old binaries from manual compiling without a package a year ago or so. For some reason they ended up in my path, so I did not actually use the binaries I built with the package... and a year ago, ABI version was still 7.

#notabug :)
