### ISSUE TITLE
Consider adding to stackage

### ISSUE THREAD

**Issue by ragreener1** [nomeata/arbtt#158]
Hi Joachim,

Would you consider adding arbtt to stackage? This would make it easier to maintain for Debian, as, as you know, we use the stackage LTS, and would mean that we can be sure it is buildable always.

Thanks!
Robert

**Comment by nomeata** [comment]
Great idea, done: https://github.com/commercialhaskell/stackage/pull/6618

**Comment by nomeata** [comment]
(I think I commented on the d-haskell mailing list, but maybe my mail didn't go through)

**Comment by ragreener1** [comment]
I may have missed it I've been away the last week and have only skimmed the list! Thanks!
