### ISSUE TITLE
arbtt-stats fails if window title very long with unmatched parenthesis

### ISSUE THREAD

**Issue by docsmooth** [nomeata/arbtt#161]
`$ arbtt-stats --dump-samples
$ arbtt-stats: Text.Regex.PCRE.Light: Error in regex: unmatched parentheses=======>.....................................................................................................................................................]  30%
CallStack (from HasCallStack):
  error, called at ./Text/Regex/PCRE/Light.hs:185:16 in pcre-light-0.4.1.0-1Z6HZ3NS79hDJiUYAa0rcp:Text.Regex.PCRE.Light

$ arbtt-dump | perl -ne 'print if ($_~~/\([^)]+(?!\))*$/);' |head -1
Smartmatch is experimental at -e line 1.
    (*) Navigator:      can't change power state from D3cold to D0 (config space inaccessible - Google Search — Mozilla Firefox
`

arbtt-recover says that the capture.log is clean, but arbtt-stats continues to crash at exactly 30% of my file. When I went looking for unmatched parenthesis in the log, I found Firefox, Chrome, and Spotify instances all having a ( but no closing ) because the title was too long for the dump.

**Comment by docsmooth** [comment]
`
-- -*- mode: haskell; -*-
-- Comments in this file use the Haskell syntax:
-- A "--" comments the rest of the line.
-- A set of {- ... -} comments out a group of lines.

-- This defines some aliases, to make the reports look nicer:
aliases (
	"sun-awt-X11-XFramePeer"  -> "java",
	"sun-awt-X11-XDialogPeer" -> "java",
	"sun-awt-X11-XWindowPeer" -> "java",
	"gramps.py"               -> "gramps",
	"___nforschung"           -> "ahnenforschung",
	"Pidgin"                  -> "pidgin"
	)

-- A rule that probably everybody wants. Being inactive for over a minute
-- causes this sample to be ignored by default.
$idle > 120 ==> tag inactive,

-- Tag web apps as such
current window $program == ["chrome","google-chrome","firefox", "Navigator"] ==> tag Web,


-- Rules to merge different apps of the same purpose together
current window $program == ["chrome","google-chrome","firefox", "Navigator"] ==> tag Program:Web,
current window $program == ["konsole","xterm","yakuake" ] ==> tag Program:Konsole,

-- Use condition bindings to reduce duplication
condition isJava = current window $program ==
  ["sun-awt-X11-XFramePeer", "sun-awt-X11-XDialogPeer", "sun-awt-X11-XWindowPeer"]
in $isJava && current window $title == "I3P" ==> tag Program:I3P,

condition isMeeting = any window ($title =~ /Webex/ || $title =~ /Meeting is in progress/ || $program == "zoom")

in {
  $isMeeting && current window ( $program == "zoom" ||  $title =~ /Webex/ || $title =~ /Meeting is in progress/ )
    ==> tag Meeting:Discussion,

  $isMeeting && current window $title =~ /Mail - Robert/
    ==> tag Meeting:Email,

  $isMeeting && current window $title =~ /(BeyondInsight|FreeRDP|xterm)/
    ==> tag Meeting:Demo,

  condition isTeams =  current window ( $program == "teams-insiders" || $program == "teams-for-linux" || $program =~ /teams.*insiders/ )

  in {
    $isMeeting && $isTeams
      ==> tag Meeting:Teams,
    $isTeams
      ==> tag Program:Teams,
    $isTeams
      ==> tag Communications:Teams,
  },
  condition isOffice = current window ( $program == "excel_exe" || $program == "winword_exe" )
    in {
      $isOffice && $isMeeting
        ==> tag Meeting:Office,
      $isOffice
        ==> tag Project:Documentation,
    },
  $isMeeting && current window $program == ["chrome","google-chrome","firefox", "Navigator"] ==> tag Meeting:Web,
  $isMeeting && current window $program == ["konsole","xterm","yakuake" ] ==> tag Meeting:Konsole,
  $isMeeting ==> tag Meeting:$current.program,
},

current window $title =~ /(Twitter|TweetDeck)/ ==> tag Personal:Twitter,
current window $title =~ /(Twitter|TweetDeck)/ ==> tag Communications:Twitter,
current window $title =~ /Facebook/ ==> tag Personal:Facebook,
current window $title =~ /Plan to Eat/ ==> tag Personal:Menu,
current window $title =~ /Sugar Beet/ ==> tag Personal:Groceries,
current window $title =~ /Whole Foods/ ==> tag Personal:Groceries,
current window $title =~ /Instacart/ ==> tag Personal:Groceries,

current window $program == "signal-desktop" ==> tag Communications:Text,
current window $program == "signal-desktop" ==> tag Personal:Text,


-- Simple rule that just tags the current program
tag Program:$current.program,

-- Another simple rule, just tags the current desktop (a.k.a. workspace)
tag Desktop:$desktop,

-- I'd like to know what evolution folders I'm working in. But when sending a
-- mail, the window title only contains the (not very helpful) subject. So I do
-- not tag necessarily by the active window title, but the title that contains
-- the folder
current window $program == "evolution" &&
any window ($program == "evolution" && $title =~ /^(.*) \([0-9]+)/)
  ==> tag Evo-Folder:$1,

-- A general rule that works well with gvim and gnome-terminal and tells me
-- what project I'm currently working on
current window $title =~ m!/workspace/([^/)]*)!
  ==> tag Unbillable:$1,
any window $title =~ m!/(svn|Documents/OneDrive-BT/Customers)/([^/_ ]*)!
  ==> tag Billable:$2,
any window ($program == "konsole" && $title =~ m!vi - "rob@.*Customers/([^/_ ]*)!)
  ==> tag Billable:$1,
any window ($program == "konsole" && $title =~ m!vi - "rob@.*Process/([^/]*)!)
  ==> tag Unbillable:$1,
any window ($program == "konsole" && $title =~ m!vi - "rob@.*Product/([^/]*)!)
  ==> tag Unbillable:$1,

current window $title =~ /Salesforce/
  ==> tag Unbillable:Admin,

current window $program == "rememberthemilk"
  ==> tag Unbillable:TaskManagement,


current window $title =~ m!HLD.*\.docx!
  ==> tag Documentation:HLD,
current window $title =~ m!LLD.*\.docx!
  ==> tag Documentation:LLD,
current window $title =~ m!(.*)PAM.*[HL]LD[^\-.a-uw-zA-UW-Z]*\.docx!
  ==> tag Billable:$1,

current window $title =~ m!VMware Workstation!
  ==> tag VM-Work,

current window $title =~ /FreeRDP/
  ==> tag Personal:Lab,
current window $title =~ /ntop/
  ==> tag Personal:Lab,

current window $title =~ m!win10-vm!
  ==> tag Windows-Desktop,

current window $title =~ /(Disney+|Hulu|Netflix|Kaffeine)/
  ==> tag Personal:Media,
current window $title =~ /Spotify/
  ==> tag Personal:Music,

current window $title =~ m!Mail - Robert!
  ==> tag Communications,

-- Out of curiosity: what percentage of my time am I actually coding Haskell?
current window ($program =~ /(konsole|bash)/ && $title =~ /^[^ ]+\.py/ )
  ==> tag Editing-Python,

current window ($program =~ /(konsole|bash)/ && $title =~ /^[^ ]+\.pl/ )
  ==> tag Editing-Perl,
current window ($program =~ /(konsole|bash)/ && $title =~ /^[^ ]+\.sh/ )
  ==> tag Editing-Bash,
current window ($program =~ /(konsole|bash)/ && $title =~ /^[^ ]+\.ps1/ )
  ==> tag Editing-PoSH,

-- To be able to match on the time of day, I introduce tags for that as well.
-- $time evaluates to local time.
$time >=  23:00 || $time <  6:00 ==> tag time-of-day:night,
$time >=  6:00 && $time < 11:30 ==> tag time-of-day:morning,
$time >= 11:30 && $time < 13:00 ==> tag time-of-day:lunchtime,
$time >= 13:00 && $time < 17:30 ==> tag time-of-day:afternoon,
$time >= 17:30 && $time < 20:30 ==> tag time-of-day:familydinner,
$time >= 20:30 && $time < 23:00 ==> tag time-of-day:late-evening,

-- This tag always refers to the last 24h
$sampleage <= 24:00 ==> tag last-day,

-- To categorize by calendar periods (months, weeks, or arbitrary periods),
-- I use $date variable, and some auxiliary functions. All these functions
-- evaluate dates in local time. Set TZ environment variable if you need
-- statistics in a different time zone.

-- You can compare dates:
$date >= 2001-01-01 ==> tag this_century,
-- You have to write them in YYYY-MM-DD format, else they will not be recognized.

-- “day of month $date” gives the day of month (1..31),
-- “day of week $date” gives a sequence number of the day of week
-- (1..7, Monday is 1):
(day of month $date == 13) && (day of week $date == 5) ==> tag day:friday_13,

-- “month $date” gives a month number (1..12), “year $date” gives a year:
month $date == 1 ==> tag month:January,
month $date == 2 ==> tag month:February,
month $date == 3 ==> tag month:March,
month $date == 4 ==> tag month:April,
month $date == 5 ==> tag month:May,
month $date == 6 ==> tag month:June,
month $date == 7 ==> tag month:July,
month $date == 8 ==> tag month:August,
month $date == 9 ==> tag month:September,
month $date == 10 ==> tag month:October,
month $date == 11 ==> tag month:November,
month $date == 12 ==> tag month:December,
year $date == 2020 ==> tag year:2020,
year $date == 2021 ==> tag year:2021,
year $date == 2022 ==> tag year:2022,

-- “$now” evaluates to the current time
(day of month $now == day of month $date) &&
  ( month $now == month $date ) &&
  ( year $now == year $date ) ==> tag current-day,
month $now == month $date ==> tag current-month,
year $now == year $date ==> tag current-year,

`

**Comment by docsmooth** [comment]
hrm, I may be completely wrong about the reason:
`arbtt-dump | perl -e '$i=0; while (<>) { if ($_=~/\([^)]+(?!\))$/){ print("$i\t$_");} if ($_=~/\d+ms (in)*active\):/) {$i++}}; print("$i\tEnd\n");'`
Shows that there are 699329 entries. Firefox showing that unclosed ( pattern shows up as early as entry 17335, and there's only 2 entries anywhere near 30% of the way through:
232352      (*) Navigator:      can't change power state from D3cold to D0 (config space inaccessible - Google Search — Mozilla Firefox

If you find a culprit in my cfg file, I'd love to be shown to be the idiot. :)

**Comment by nomeata** [comment]
This one probably:
```
any window ($program == "evolution" && $title =~ /^(.*) \([0-9]+)/)
```

It is actually from my very own configuration file, but there it says
```
any window ($program == "evolution" && $title =~ /^(.*) \([0-9]+/)
```
so somehow an extra parens made it into your file maybe?

**Comment by docsmooth** [comment]
So I straced it and the last read is:
`read(3, "Net\1\0\0\0\3508\1\1\0\0\0\0\0\0\0\6\361\20\5\257\337\7\0\7sY@\0\0"..., 32752) = 32752
read(3, "\0\0\0\0\0\0\0\3Net\1\0\0\0\3509\1\1\0\0\0\0\0\0\0\6\335\21J\327\17"..., 32752) = 32752
read(3, "\0\6\331#=\326}\6\0\16\346\262\200\0\0\0\352`\3\0\0\0\0\0\0\0\10\0\1\2\0\3"..., 32752) = 32752
read(3, "\0\0\0\0\0\3RDP\1\0\0\0\3509\1\1\0\0\0\0\0\0\0\5\25\276\3445\272\0\0"..., 32752) = 32752
read(3, "\0\5\6\0\t\n\0\v\f\0\r\16\0\17\16\1\21\22\0\23\24\0\0\0\0066\0\0\0\0\0\0"..., 32752) = 32752
read(3, "\5\6\0\5\6\0\t\n\0\v\f\0\r\16\0\17\16\0\21\22\0\23\24\0\25\26\1\27\30\0\0j"..., 32752) = 32752
read(3, "\16\0\21\22\0\23\24\0\25\26\1\27\30\0\1\252\220\376\0\0\0\0\0\0\0\0\3RDP\1\0"..., 32752) = 32752
read(3, "E\202\0\0\0\0\0\0\0\0\3RDP\1\0\0\0\350:\1\1\0\0\0\0\0\0\0\6\221\277"..., 32752) = 32752
read(3, ")\n\0\0\0\0\0\0\0\0\3Net\1\0\0\0\350:\1\1\0\0\0\0\0\0\0\6_1"..., 32752) = 32752
read(3, "\0\5\6\0\5\6\0\t\n\0\v\f\0\r\f\1\17\20\0\21\22\0\23\24\0\25\24\0\0\0=Z"..., 32752) = 32752
read(3, "\0\0\0\3Net\1\0\0\0\350;\1\1\0\0\0\0\0\0\0\6\357\347\331.\205\6\0\35\315"..., 32752) = 32752
read(3, "\r\f\0\17\20\0\21\22\0\23\24\0\25\26\0\27\25\0\25\26\0\27\25\0\0$\317\376\0\0\0\0"..., 32752) = 32752
read(3, "\0\350;\1\1\0\0\0\0\0\0\0\6\3\271|\375\301\v\0\16\346\262\200\0\0\0\352`\3\0\0"..., 32752) = 32752
read(3, "\0\3\2\0\5\6\0\7\10\0\7\10\1\v\f\0\r\16\0\17\20\0\21\20\0\0\0\0\254\0\0\0"..., 32752) = 32752
read(3, "\212B\0\0\0\0\0\0\0\0\3CMD\1\0\0\0\350<\1\1\0\0\0\0\0\0\0\6\235 "..., 32752) = 32752
read(3, "\0\3\2\0\5\6\0\7\10\0\7\10\0\v\f\0\r\16\0\2]\303\372\0\0\0\0\0\0\0\0\3"..., 32752) = 32752
read(3, "\0\0\0\0\0\0\6\321P\271\226S\t\0\v\353\302\0\0\0\0\352`\3\0\0\0\0\0\0\0\v"..., 32752) = 32752
read(3, ":0:bash - \"rob@l-7k0s2z2: /home/"..., 32752) = 32752
read(3, "\v\f\0\r\16\0\7\10\0\0\201\361\322\0\0\0\0\0\0\0\0\3Net\1\0\0\0\350=\1"..., 32752) = 32752
read(3, "\0\r\16\0\17\20\0\0\265\211\23\0\0\0\0\0\0\0\0\3Net\1\0\0\0\350=\1\1\0"..., 32752) = 32752
read(3, "\0\0\0\10\0\1\2\0\3\2\0\5\6\0\7\10\0\7\10\0\v\f\0\r\16\0\17\20\0\2&\5"..., 32752) = 32752`

Checking into the cfg since you posted at the same time as me.

**Comment by docsmooth** [comment]
Confirming you are correct - the extra closing paren in the evolution line is the problem!

$ arbtt-stats
Processing data [=====================================================================================================================================================================================================================] 100%
Total time per tag
==================
_________________________________________Tag_|__________Time_|_Percentage_
                                this_century | 113d22h58m00s |     100.00
                                 Desktop:Net |  75d04h42m00s |      65.99

**Comment by nomeata** [comment]
What difference a small character can make :-)

Anyways, glad you like the tool :-)
