### ISSUE TITLE
[BUG] Error calling arbtt-stats on Debian 11 (Timelog starts with unknown marker)

### ISSUE THREAD

**Issue by jerlendds** [nomeata/arbtt#164]
Hi, I saw this app a long time ago but I've been having issues getting it working on my system and I don't see any alternatives that accomplish what this great program seems to promise.

I have created a `~/.arbtt/categorize.cfg` file populated with the details from [Example One in the docs](https://arbtt.nomeata.de/doc/users_guide/configuration.html) and I have tried installing from source and also from the Debian package repo but I consistently get the below error when running `arbtt-stats`:
```sh
jerlendds@devlab:~$ arbtt-stats
arbtt-stats: Timelog starts with unknown marker "\n\SOH\NUL\NUL\NUL\233\228\SOH\SOH\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ACK".........................]   0%
CallStack (from HasCallStack):
  error, called at src/TimeLog.hs:116:13 in main:TimeLog

```

Heres the output of me running `cat ~/.arbtt/capture.log`
![image](https://user-images.githubusercontent.com/29207058/197521810-4d5097b9-8647-4af9-9567-5737d1980fa6.png)

It seems as if the data being saved is being corrupted somehow during the save process and Ive started trying to investigate the issue myself but I have never used Haskell before so progress is slow. Any tips or help would be greatly appreciated!

**Comment by jerlendds** [comment]
> Your log file somehow got corrupted. If you have not used arbtt before and have no data there to retain, I suggest you kill `arbtt-capture`, delete the log file, and restart `arbtt-capture`. Hopefully that should fix it

Thanks for the help @nomeata ! arbtt is working now :D, I'm thinking of developing a visualization tool for this once I have more time. Previously I tried `rm`ing the log file, `touch ~/.arbtt/capture.log`, and then starting up `arbtt-capture` but I'm guessing since I created the initial `capture.log` file manually it was causing issues when I tried to start up arbtt again

**Comment by nomeata** [comment]
That could be, maybe the header is only written when the file does not already exist.
