### ISSUE TITLE
Logrotate and arbtt-capture

### ISSUE THREAD

**Issue by uhausbrand** [nomeata/arbtt#178]
Hi,
I want to automate the backup of the log file and want to use logrotate with the following config:

```
/home/USER/.arbtt/capture.log
{
        su USER USERGROUP
        nomail
        nocreate
        yearly
        missingok
        rotate 10
        dateext
        firstaction
        pkill arbtt-capture
        endscript
        lastaction
        arbtt-capture --sample-rate 30 &
        endscript
}
```
I stop the capture process before rotating the logfile so to not have any issues with the binary file.
My issue is that even if I restart the abrtt-capture process, it doesn't log anything anymore.

Would it be possible to have arbtt-capture handle logrotation gracefully? Or any ideas how I could achieve this?

**Comment by nomeata** [comment]
I assume the restart doesn’t work because when it is started from `logrotate`, the `DISPLAY` variable isn’t set. You could try to hack around it (`DISPLAY=:0 arbttt-capture`).

**Comment by uhausbrand** [comment]
Thank you for your input. That's right, it was missing the Display variable.
For completeness if somebody wonders what to do:
```
/home/USER/.arbtt/capture.log
{
        su USER USERGROUP
        nomail
        nocreate
        yearly
        missingok
        rotate 10
        dateext
        firstaction
        pkill arbtt-capture || true
        endscript
        lastaction
        (DISPLAY=:0 runuser -u USER -- arbtt-capture --logfile /home/USER/.arbtt/capture.log --sample-rate 30 &)
        endscript
}
```
