### ISSUE TITLE
Configure fails with missing dependencies

### ISSUE THREAD

**Issue by MatthewScholefield** [nomeata/arbtt#21]
I get the following when running `runhaskell Setup.hs configure`:
```
runhaskell Setup.hs configure

Setup.hs:26:17: warning: [-Wdeprecations]
    In the use of ‘rawSystemProgram’
    (imported from Distribution.Simple.Program):
    Deprecated: "use runProgram instead"
   |
26 |                 rawSystemProgram verb configuredProg
   |                 ^^^^^^^^^^^^^^^^
Configuring arbtt-0.10.0.2...
Setup.hs: Encountered missing dependencies:
X11 >=1.9,
bytestring-progress -any,
pcre-light -any,
strict -any,
terminal-progress-bar ==0.2.*
```
Note: I'm running on Solus (not Ubuntu based), but I have installed the `libxrandr-dev` equivalent and compiled/installed `libxss-dev` from source.

Any help would be appreciated :)
Thanks.

**Comment by nomeata** [comment]
Do you have the `cabal` tool in Solus? In that case, try running `cabal install` instead.

**Comment by nomeata** [comment]
What is your version of `ghc` and `cabal`?

But this look like a solus-specific problem and maybe you will have more luck in their support channels.

**Comment by GladOSkar** [comment]
For future souls users discovering this thread:

Install the `ghc-devel` package. It contains the missing header files.

**Comment by nomeata** [comment]
Great, thanks!
