### ISSUE TITLE
Possible to capture additional data from other sources?

### ISSUE THREAD

**Issue by isovector** [nomeata/arbtt#28]
I'd like to associate data from an external process to my arbtt captures. Is this possible today, or do I need to do some hacking?

**Comment by isovector** [comment]
In particular I'd like to run an `Show a => IO a` action every time a capture occurs, and keep/categorize on the resultant `a`.

**Comment by nomeata** [comment]
You can either do it externally by writing a program that creates a window with the information you need in the title, and then match on that (that’s what most people do). Or you can of course do a local hack within arbtt.

**Comment by isovector** [comment]
Spinning up an extra window sounds like it's asking for trouble, between having it always be running and invisible. Would you be receptive to a patch that adds a "virtual window" in the config that just reads a file at capture-time? Other programs could hook into this functionality by writing to the file regularly.

**Comment by isovector** [comment]
So what I'm actually trying to do is to hook up the readings from a [MindWave](https://store.neurosky.com/pages/mindwave) and cross reference them against what I'm working on at the time. I don't actually want to _categorize_ on this data, merely that arbtt seems like a convenient place to store this info until I can chart it with `arbtt-graph`.

Maybe on second thought this would be better done as keeping a second data source and joining them in `arbtt-graph`?

**Comment by nomeata** [comment]
>  Would you be receptive to a patch that adds a "virtual window" in the config that just reads a file at capture-time? 

I am hesitant, mostly on the grounds that `arbtt` is effectively in mostly maintenance mode…

**Comment by isovector** [comment]
Sounds good. I'll find a way to work around it. Thanks for `arbtt` though, it's a fantastic piece of software!

**Comment by nomeata** [comment]
> Thanks for arbtt though, it's a fantastic piece of software!

Glad to hear :-D
