### ISSUE TITLE
arbtt-stats: Unsupported TimeLogEntry version tag 0

### ISSUE THREAD

**Issue by isovector** [nomeata/arbtt#29]
I'm getting the following error when running `arbtt-stats`

```
arbtt-stats: Unsupported TimeLogEntry version tag 0
CallStack (from HasCallStack):
  error, called at src/Data.hs:90:15 in main:Data
```

**Comment by nomeata** [comment]
That can happen when the log file got corrupted, which is not that unlikely. See http://arbtt.nomeata.de/doc/users_guide/arbtt-recover.html

**Comment by isovector** [comment]
That fixes it, thanks!

**Comment by nomeata** [comment]
Likely just an ungraceful shutdown of the capture program. Or maybe multiple ones running at the same time?

Linux or OSX? What is your sample rate?
