### ISSUE TITLE
parse error in the sample configuration

### ISSUE THREAD

**Issue by krishnaghatti** [nomeata/arbtt#31]
I used the `categorize.cfg` from the repo as my initial configuration and when i try to check the stats, i get the below error. Am i missing something basic?

OS : elementaryOS

`$ arbtt-stats       
Parser error:
"/home/user/.arbtt/categorize.cfg" (line 24, column 1):
unexpected 'c'
expecting "{", "(", "[", variable, regular expression, string, time, date, number, "if", "tag" or end of input
`

UPDATE: arbtt version being used 

`arbtt:
  Installed: 0.9.0.13-1
  Candidate: 0.9.0.13-1
  Version table:
 *** 0.9.0.13-1 500
        500 http://in.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status`

**Comment by nomeata** [comment]
Hmm, `conditions` were added by @markus1189 . Markus, can you have a look?

**Comment by markus1189** [comment]
I think the `let` bindings for conditions are not available before 0_9_0_13-23-ge07a541 :slightly_smiling_face: 

@krishnaghatti the reason for the error is that your version of `arbtt` is quite old, I would suggest to upgrade to a newer version if you can.

**Comment by krishnaghatti** [comment]
@markus1189 thank you for the update. the version was the issue. i added the config from the older version and it is working as expected. i am getting a few missing dependencies when trying to compile from the source and with cabel as well. i will check on how to resolve them.
