### ISSUE TITLE
log compression

### ISSUE THREAD

**Issue by misev** [nomeata/arbtt#33]
Compressing the log could dramatically reduce the size. Especially if we consider that the number of applications and window titles will not vary so much over time.

gzip is pretty popular on Linux, with several utilities having versions to support gzipped files (zless, zcat, zgrep, zdiff, etc). It might fit well for arbtt too; I see 4x smaller log when compressed with gzip. Concatenating gzip streams is possible, and periodically arbtt-capture could recompress larger chunks as this will likely improve the compression a lot.

**Comment by nomeata** [comment]
Note that within one session arbtt already avoids writing window titles if they were in the previous sample. Helps a bit.

But yeah, probably useful… right now arbtt is built around the idea that it can simply append each chunk individually. Simple … but less reliable than I hoped back then :-)

There are also calls for using a proper database (sqlite), also for less often corrupted logs. Maybe that would be the best option.

I currently don’t plan to invest significant amount of work into arbtt, though…

**Comment by misev** [comment]
> I currently don’t plan to invest significant amount of work into arbtt, though…

Fair enough :) The issue could stay open, maybe someone else knowledgeable in haskell will be interested to pick it up. The data collected by arbtt is not that big in any case, I suppose less than 1 GB per year.

**Comment by nomeata** [comment]
Much less:
```
~ $ ls -sh .arbtt/capture.log
165M .arbtt/capture.log
~ $ arbtt-stats -i
General Information                                                                               
===================
                       FirstRecord |    2009-08-21 10:16:44.951741 UTC
                        LastRecord | 2020-04-13 19:47:02.565039576 UTC
                 Number of records |                           1649353
               Total time recorded |                    1145d09h13m00s
               Total time selected |                     818d20h00m00s
   Fraction of total time recorded |                               29%
   Fraction of total time selected |                               21%
Fraction of recorded time selected |                               71%
```

**Comment by misev** [comment]
Ah I thought it's more. I used arbtt a while ago and just started running it again. Back than I recall that some 1-2 GB were collected, but I may have put a very fine resolution. Ok I'd close this issue then, it doesn't sound worth it.

**Comment by nomeata** [comment]
I think many new users think the default resolution is to little and ramp it up. But if you get many samples (and depending on what you want to know) the default resolution is just fine, I think.
