### ISSUE TITLE
user contributed categorize.cfg files

### ISSUE THREAD

**Issue by pas-calc** [nomeata/arbtt#49]
Is there the idea to **build up a list of user contributed categorize.cfg files**? Or   to have a handy tool that creates a cfg file based on simplified user input or even a tool that uses ideas of [Effective Use of Arbtt](https://arbtt.nomeata.de/doc/users_guide/effective-use.html) to support workflow in the setup process?
This cfg file database would serve as _templates_ so that other users can use them as _presets_ to build their own, especially for those that are not too much inclined in programming (maybe this tool is rather for coders though;) 

The syntax should be explained with comments, two things I dont understand:
- is the `mode:haskell` at the beginning crucial?
- the `m!..!` rule is not standard regex? 
- is regex in array `=~ [.., ..,]` the same as in one string `=~ /..|...|../` ?
- is regex for _start of line_ (or do I need to start with `.*` if its not in beginning of line), or is it that one needs caret^ to define start of line (same for _end of line_ `^ / $`) ?

**Comment by liskin** [comment]
I have [a tool in my ~/bin](https://github.com/liskin/dotfiles/blob/home/bin/liskin-arbtt-stats), aliased to `arbtt` which simplifies usage of arbtt:

* `arbtt with-uncategorized-nofallback dump-current-window today` wraps the `--exclude | fgrep | sort | uniq` pipeline from Effective Use, and there's also `with-uncategorized` that excludes some catchall/fallback tags as well and shows only truly uncategorized samples
* `arbtt activity-chart today` (or just `arbtt activity-chart` or `arbtt`) wraps `arbtt-stats | arbtt-chart` and gives me a visual summary of what I've done so far that day (needs https://github.com/liskin/arbtt-chart), and there's a systemd timer that e-mails me yesterday's chart every morning

Speaking of a list of user-contributed categorize.cfg files, I wouldn't mind if [my categorize.cfg](https://github.com/liskin/dotfiles/blob/home/.arbtt/categorize.m4) was included in a list somewhere.

**Comment by nomeata** [comment]
I could enable the GitHub wiki for this repo, if that'd help?

**Comment by pas-calc** [comment]
> I could enable the GitHub wiki for this repo, if that'd help?

That would help indeed,

**Comment by nomeata** [comment]
Done! Also the discussions feature, maybe it’s useful.
